using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Guessing_Game
{
    class RandomInteger
    {
       //the random method will generate the random number
        protected Random random = new Random(int.Parse(Guid.NewGuid().ToString().Substring(0, 8), System.Globalization.NumberStyles.HexNumber));
        protected int currentRandomNumber = 0;

        public RandomInteger()
        {

        }

        public int GenerateRandomNumber()
            //this method will assign the random number to a data member
        {
            currentRandomNumber = random.Next();
            return currentRandomNumber;
        }

        //this is the getter for the random number generated by the random method.
        public int GetCurrentRandomNumber() { return currentRandomNumber; }
    }
}
